"""multi_commerce_v1

Revision ID: d9ba94f281ec
Revises: 
Create Date: 2026-03-23 22:24:06.135178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ba94f281ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('merchant_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('requested_category_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_applications_id'), 'merchant_applications', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_applications_status'), 'merchant_applications', ['status'], unique=False)
    op.create_index(op.f('ix_merchant_applications_user_id'), 'merchant_applications', ['user_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('accepting_orders', sa.Boolean(), nullable=False),
    sa.Column('opening_note', sa.String(length=160), nullable=True),
    sa.Column('min_delivery_minutes', sa.Integer(), nullable=False),
    sa.Column('max_delivery_minutes', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['merchant_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_owner_user_id'), 'stores', ['owner_user_id'], unique=True)
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    op.create_index(op.f('ix_stores_status'), 'stores', ['status'], unique=False)
    op.create_table('mercadopago_credentials',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_slug'), 'product_categories', ['slug'], unique=False)
    op.create_index(op.f('ix_product_categories_store_id'), 'product_categories', ['store_id'], unique=False)
    op.create_table('shopping_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=40), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_carts_id'), 'shopping_carts', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_carts_store_id'), 'shopping_carts', ['store_id'], unique=False)
    op.create_index(op.f('ix_shopping_carts_user_id'), 'shopping_carts', ['user_id'], unique=True)
    op.create_table('store_category_links',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id', 'category_id')
    )
    op.create_table('store_delivery_settings',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('delivery_enabled', sa.Boolean(), nullable=False),
    sa.Column('pickup_enabled', sa.Boolean(), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('store_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_hours_day_of_week'), 'store_hours', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_store_hours_id'), 'store_hours', ['id'], unique=False)
    op.create_index(op.f('ix_store_hours_store_id'), 'store_hours', ['store_id'], unique=False)
    op.create_table('store_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=40), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('payment_status', sa.String(length=40), nullable=False),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=180), nullable=False),
    sa.Column('store_name_snapshot', sa.String(length=180), nullable=False),
    sa.Column('store_slug_snapshot', sa.String(length=180), nullable=False),
    sa.Column('store_address_snapshot', sa.Text(), nullable=False),
    sa.Column('address_label_snapshot', sa.String(length=80), nullable=True),
    sa.Column('address_full_snapshot', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_orders_address_id'), 'store_orders', ['address_id'], unique=False)
    op.create_index(op.f('ix_store_orders_id'), 'store_orders', ['id'], unique=False)
    op.create_index(op.f('ix_store_orders_payment_reference'), 'store_orders', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_store_orders_status'), 'store_orders', ['status'], unique=False)
    op.create_index(op.f('ix_store_orders_store_id'), 'store_orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_orders_user_id'), 'store_orders', ['user_id'], unique=False)
    op.create_table('store_payment_settings',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('cash_enabled', sa.Boolean(), nullable=False),
    sa.Column('mercadopago_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('store_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_products_id'), 'store_products', ['id'], unique=False)
    op.create_index(op.f('ix_store_products_product_category_id'), 'store_products', ['product_category_id'], unique=False)
    op.create_index(op.f('ix_store_products_store_id'), 'store_products', ['store_id'], unique=False)
    op.create_table('shopping_cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=180), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_cart_items_cart_id'), 'shopping_cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_shopping_cart_items_id'), 'shopping_cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_cart_items_product_id'), 'shopping_cart_items', ['product_id'], unique=False)
    op.create_table('store_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=180), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['store_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_order_items_id'), 'store_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_store_order_items_order_id'), 'store_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_store_order_items_product_id'), 'store_order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_order_items_product_id'), table_name='store_order_items')
    op.drop_index(op.f('ix_store_order_items_order_id'), table_name='store_order_items')
    op.drop_index(op.f('ix_store_order_items_id'), table_name='store_order_items')
    op.drop_table('store_order_items')
    op.drop_index(op.f('ix_shopping_cart_items_product_id'), table_name='shopping_cart_items')
    op.drop_index(op.f('ix_shopping_cart_items_id'), table_name='shopping_cart_items')
    op.drop_index(op.f('ix_shopping_cart_items_cart_id'), table_name='shopping_cart_items')
    op.drop_table('shopping_cart_items')
    op.drop_index(op.f('ix_store_products_store_id'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_product_category_id'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_id'), table_name='store_products')
    op.drop_table('store_products')
    op.drop_table('store_payment_settings')
    op.drop_index(op.f('ix_store_orders_user_id'), table_name='store_orders')
    op.drop_index(op.f('ix_store_orders_store_id'), table_name='store_orders')
    op.drop_index(op.f('ix_store_orders_status'), table_name='store_orders')
    op.drop_index(op.f('ix_store_orders_payment_reference'), table_name='store_orders')
    op.drop_index(op.f('ix_store_orders_id'), table_name='store_orders')
    op.drop_index(op.f('ix_store_orders_address_id'), table_name='store_orders')
    op.drop_table('store_orders')
    op.drop_index(op.f('ix_store_hours_store_id'), table_name='store_hours')
    op.drop_index(op.f('ix_store_hours_id'), table_name='store_hours')
    op.drop_index(op.f('ix_store_hours_day_of_week'), table_name='store_hours')
    op.drop_table('store_hours')
    op.drop_table('store_delivery_settings')
    op.drop_table('store_category_links')
    op.drop_index(op.f('ix_shopping_carts_user_id'), table_name='shopping_carts')
    op.drop_index(op.f('ix_shopping_carts_store_id'), table_name='shopping_carts')
    op.drop_index(op.f('ix_shopping_carts_id'), table_name='shopping_carts')
    op.drop_table('shopping_carts')
    op.drop_index(op.f('ix_product_categories_store_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_slug'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_table('mercadopago_credentials')
    op.drop_index(op.f('ix_stores_status'), table_name='stores')
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_index(op.f('ix_stores_owner_user_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_merchant_applications_user_id'), table_name='merchant_applications')
    op.drop_index(op.f('ix_merchant_applications_status'), table_name='merchant_applications')
    op.drop_index(op.f('ix_merchant_applications_id'), table_name='merchant_applications')
    op.drop_table('merchant_applications')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
